name: pre-commit (prek)

on:
  pull_request_target:
    types: [opened, synchronize]
    branches: [ "lille" ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ./src/transformation/dbt_paris_event_analyzer/profiles/
      DBT_PROJECT_DIR: ./src/transformation/dbt_paris_event_analyzer/
      DBT_ENV_SECRET_MINIO_ACCESS_KEY: ${{ secrets.DBT_ENV_SECRET_MINIO_ACCESS_KEY }}
      DBT_ENV_SECRET_MINIO_SECRET_KEY: ${{ secrets.DBT_ENV_SECRET_MINIO_SECRET_KEY }}
      PYTHON: "3.12"

    steps:
      - name: Check out ${{ github.repository }} PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.11.x"
          enable-cache: true
          cache-dependency-glob: |
            **/pyproject.toml
            **/uv.lock
      - name: Run pre-commit hooks via prek
        run: uvx prek run --all-files
